### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/notificationbar-API#1]
- [ ] 1) The API now requires a windowId to identify the window, where the notificationbox should be added. The getNotificationBox function still tries all different known notification boxes, I think with the windowId we can get the type and just use the correct one. We should also add code to create a new notificationbox, if there is none.

- [ ] 2) The priority needs to be decoupled from the internal names

- [x] 3) The onButtonClicked event listener returns the label of the clicked button to the caller. Is that needed?
-> Resolved: use an Id
- [ ] 3b) Should we check for uniqueness of button Ids?

- [ ] 4) The closed event listener returns a closedByUser bool. Is that needed to be compatible with the notification API?

- [ ] 5) I only worked on the APIs create function. I have not looked at any of the other things defined in the schema.

- [x] 6) There is still something strange, when the box gets dismissed and the add-on gets reloaded: It tries to remove the box and fails. it is probably something simple, but I fail to see it. Need more coffee.

**Comment by jobisoft** [comment]
Regarding 3)

I change the listener to return the button name, as the label could be localized and is therefore not helpful in identifiying the button. I picked name and not id, as two buttons could have the same name/actions. 

Or should it be an Id indeed?

**Comment by esellier** [comment]
Can't get it... "I picked name and not id, as two buttons could have the same name/actions."
So, if you can have two buttons with the same name, then you need the Id to differentiate which one fired the event. Except if both names should have the same action (then why two?).
In my case, I use the label and compare the label with the localized possible labels.
But an ID could be fine, why not both?

**Comment by jobisoft** [comment]
> why not both?

To simplify things. You can use the name as an id (using unique names) but it is common understanding that ids should be unique. So if you have two buttons in different notificationboxes which should do the same thing, it would be natural to give them the same name, but giving them the same id would feel strange.

On the other hand, one could simply check for multiple ids in the onClick listener.

I have no strong feeling in either direction, but using both will complicate the code, probably. Comparing against a localizable label does not feel like a good idea.

If we go for id, should it be an integer or string?

**Comment by esellier** [comment]
OK.
Then, go for the ID. As a string, since it is more generic

**Comment by jobisoft** [comment]
Done. Should we actually check for uniqueness?

**Comment by jobisoft** [comment]
Regarding 6)

The issue was bad event processing. We need proper event specifications. I added an onDismissed event.

So we have three events now:
* onButtonClicked : When a button is clicked, returns notificationId and buttonId. If a registered listener returns true, the notification bar will not be closed.
* onDismissed : When the user hits the "x" of the notification, returns notificationId.
* onClosed : When a notification is closed, returns notificationId. Is triggered either by
  * button
  * dismissal
  * manually calling remove()
  * api shutdown (window close or whatever)

Is that the desired behaviour? 

Regarding 4)

I think onClosed is supposed to return a "byUser" parameter. In which cases should that be true?

**Comment by jobisoft** [comment]
So, as things are still being optimized, this is now moved here: https://github.com/thundernest/addon-developer-support/issues/47

Sorry.
