### ISSUE TITLE
Security-check the API parameters

### ISSUE THREAD

**Issue by benbucksch** [jobisoft/notificationbar-API#4]
The experiment runs with system privileges. The extension is supposed to be confined in its rights.
That means that the extension API is a critical security boundary.

For example, if the extension passes a URL as parameter and the experiment executes it, the URL runs with system privileges. So, URLs need to be checked. Particularly, you want to be careful about `javascript:` and `data:` URLs. `data:image/png` is probably fine, but `data:text/javascript` or `data:text/html` are not.

The same is true for most other datatypes. The schema can at least check for you that you're getting a boolean when you're expecting a boolean, but you need to be more careful with strings. For strings, it depends on how they're being used later on. If you accept a label and put it into a XUL window using `.innerHTML`, you just gave the extension full system access.

The safest approach is to check the parameters immediately when you receive them and take them in (not when you're using them). Use a whitelist approach, to check that the parameter adheres to what you expect. Everything not whitelisted throws an exception.

So, you can have different functions for parameter checks, depending on its intended use.
* One function allows only image URLs
* another function allows HTML URLs (but then you need to later ensure that they are loaded in a sandboxed frame)
* one function checks strings that will be used as labels in the UI (but you still cannot use innerHTML later)
etc..

**Comment by jobisoft** [comment]
Thanks for putting this together. I will merge it into our Experiment guide, as that should be known by all developers.

**Comment by benbucksch** [comment]
Thank you!

This also applies to this API concretely, as there are several parameters that look dangerous to me when left unchecked.

**Comment by jobisoft** [comment]
In #8 I made sure, only local files (shipped with the add-on) can be used. In #9 I sanitized styles. What else do we have to look out for? The WebExtension framework does type check already on its own.

**Comment by benbucksch** [comment]
@jobisoft : I've mentioned a number of examples in my description above. Many of these examples apply here, for various parameters.

I deliberately left it as exersize for the reader to find all instances, because this won't be the last API you create, and it's more about the security mindset and security process than about individual bug instances here in this API.

**Comment by jobisoft** [comment]
Difficult to handle such an unspecific issue. I think Arnd fixed all of them.

**Comment by benbucksch** [comment]
> check the parameters immediately when you receive them
> [i.e. as first code inside an API function]

Has this been done for all functions and writable properties exposed via the API?
